# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2a0a03c75f29d26759719b1c817b92b309e8a4c3df9bdbf5a2f8e0842d0da8996fd7c0cc212f54fb741eefed91ca964c62b50483ff51de9cf3739be93db341f

test:
  secret_key_base: 835a1bdb47161f9ae893166374ed64ae9071d9b71040ba1a0c84855dcd3d1f2e50e9b9eab69ead01a2d536bacd99e3023b975d847c5ed2a954f15fc613f21c59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
